# Generated by Django 4.2.6 on 2023-11-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.hugosrestaurant.net%2Fstore%2Fcatering%2F&psig=AOvVaw2mRfm31DAMFqINFE409dAB&ust=1699703476503000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCMimqIGvuYIDFQAAAAAdAAAAABAE', max_length=1000),
        ),
    ]
