# Generated by Django 4.2.6 on 2023-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://img.freepik.com/free-vector/polygonal-restaurant-menu_23-2147491107.jpg?w=740&t=st=1699622824~exp=1699623424~hmac=6d4615708d3d99169f2e044f330a6e16bc2a149989716291ae3e128658b56457', max_length=1000),
        ),
    ]
