# Generated by Django 4.2.9 on 2024-01-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sqlquery", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Produce", new_name="Product",),
    ]
